// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7GZg2fBMM3lAZgvwfdsneMs7wvFAaAcE',
    appId: '1:372603808557:web:7cd29bac7c3659a98081a4',
    messagingSenderId: '372603808557',
    projectId: 'chapter-chatters-1b102',
    authDomain: 'chapter-chatters-1b102.firebaseapp.com',
    databaseURL: 'https://chapter-chatters-1b102-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chapter-chatters-1b102.appspot.com',
    measurementId: 'G-HZ34KD73BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK06ltiwOWrEUbE-lzHDkKWJjW5hMzixo',
    appId: '1:372603808557:android:df5686188732d5cc8081a4',
    messagingSenderId: '372603808557',
    projectId: 'chapter-chatters-1b102',
    databaseURL: 'https://chapter-chatters-1b102-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chapter-chatters-1b102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5qSOstBrQrPWl-f7617JzcXiMtlPIwhg',
    appId: '1:372603808557:ios:183a713d1b5c05338081a4',
    messagingSenderId: '372603808557',
    projectId: 'chapter-chatters-1b102',
    databaseURL: 'https://chapter-chatters-1b102-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chapter-chatters-1b102.appspot.com',
    androidClientId: '372603808557-jfl04c9ghl2dmumuedk18q0stc0d4ipg.apps.googleusercontent.com',
    iosClientId: '372603808557-9mr2b677k5f4qhlqo4bde0eaib49590p.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookApp',
  );
}
