// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACeknQHHZKi9ZnwMQkGk1SVMzS5ijNfqs',
    appId: '1:616778244680:web:a9e41e1763caf86c46ee7d',
    messagingSenderId: '616778244680',
    projectId: 'chapter-chatters',
    authDomain: 'chapter-chatters.firebaseapp.com',
    storageBucket: 'chapter-chatters.appspot.com',
    measurementId: 'G-1F0M6N0PE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW0Kq6Q6Enmo7MEcXo9TpKbUQfjf3mDt0',
    appId: '1:616778244680:android:0d9ff8785786a4e946ee7d',
    messagingSenderId: '616778244680',
    projectId: 'chapter-chatters',
    storageBucket: 'chapter-chatters.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd8h4rJ6vVlZ77wY3XaUmjoCv0DDz7Y0o',
    appId: '1:616778244680:ios:baf21a69d7a5cdb046ee7d',
    messagingSenderId: '616778244680',
    projectId: 'chapter-chatters',
    storageBucket: 'chapter-chatters.appspot.com',
    iosClientId: '616778244680-8t7njqnsf3ad891n7qbu6kiul4q52e6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd8h4rJ6vVlZ77wY3XaUmjoCv0DDz7Y0o',
    appId: '1:616778244680:ios:baf21a69d7a5cdb046ee7d',
    messagingSenderId: '616778244680',
    projectId: 'chapter-chatters',
    storageBucket: 'chapter-chatters.appspot.com',
    iosClientId: '616778244680-8t7njqnsf3ad891n7qbu6kiul4q52e6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookApp',
  );
}
